### ISSUE TITLE
Incorrect data

### ISSUE THREAD

**Issue by 0E800** [datitisev/flarum-ext-admindashboard#7]
How does this extension resolve the amount of users? Posts?

Extension says I have 27 users. I only have 3.
Extension correctly displays total amount of topics.
Extension is unable to determine total posts.

Where can I find the code to manipulate this data to be more accurate?

Best regards,

**Comment by dsevillamartin** [comment]
@0E800 This extension currently uses the ID of the last item to count the users, discussions, and posts.

Users: If it says 27 users, it means the most amount of users you've had is 27, as the last created user's ID is 27
Posts: Currently, the API endpoint `/api/posts` returns 500 Internal Server Error, that's why it shows `???`

To make it more accurate, I'd have to make my own API endpoint. I currently do not have the knowledge and time required to do so.

https://github.com/datitisev/flarum-ext-admindashboard/blob/master/js/admin/src/components/WidgetGraph.js#L56 is where the data is gotten.

The variable `posts` is made `???` automatically because https://discuss.flarum.org/api/posts returns 500.

**Comment by 0E800** [comment]
Thank you for your prompt response. Thank you for the information I requested. Have a happy Friday the 13th 👍 

I believe the number is at 27 due to the amount of test users I created and deleted. When a user is deleted, the ID# does not go back.

**Comment by dsevillamartin** [comment]
@0E800 Exactly. Closing this for now.

If you feel this is very important, and just **need** to know how many posts, discussions, and users there are, please feel free to re-open.

Related to #5

**Comment by 0E800** [comment]
Is it possible to get an accurate post count with a sql query? I'm only able to barely read code in so much as manipulate data. I would like to try to add to your dashboard extension but I would like to know if it's possible to just add php code that queries the data base from all users, count total posts and echo that to the dashboard.

Is it the API that provides the means to query the flarum db?
